export const radioStations = [
  {
    id: "imbat-fm",
    name: "İmbat FM",
    frequency: "Tam 90",
    description: "Yeni Dostunuz",
    color: "bg-gradient-to-r from-green-600 to-green-800",
    genre: "Hit Müzik",
    streamUrl: `https://cors-anywhere.herokuapp.com/http://162.244.80.31:8746/;`,
  },
  {
    id: "kordon-fm",
    name: "Kordon FM",
    frequency: "96.5",
    description: "İzmir'in Sesi",
    color: "bg-gradient-to-r from-blue-600 to-blue-800",
    genre: "Pop & Rock",
    streamUrl: "http://162.244.80.31:8846/;",
  },
  {
    id: "radyo-kordelya",
    name: "Radyo Kordelya",
    frequency: "88.5",
    description: "Klasik ve Sanat",
    color: "bg-gradient-to-r from-purple-600 to-purple-800",
    genre: "Klasik & Sanat",
    streamUrl: "http://162.244.80.31:8646/;",
  },
  {
    id: "imbat-slow",
    name: "İmbat Slow",
    frequency: "107.6",
    description: "Sakin Müzik",
    color: "bg-gradient-to-r from-orange-600 to-orange-800",
    genre: "Slow & Chill",
    streamUrl: "http://38.96.148.39:8946/;",
  },
  {
    id: "imbat-haber",
    name: "İmbat Haber",
    frequency: "94.2",
    description: "Haber Radyosu",
    color: "bg-gradient-to-r from-gray-600 to-gray-800",
    genre: "Haber",
    streamUrl: "http://38.96.148.134:8688/;",
  },
];
