import {
  RadioStationData,
  RadioStationsTexts,
} from "@/components/StationInformation/StationInformation.types";

export const stationsInformation: RadioStationData[] = [
  {
    id: "1",
    name: "İmbat FM",
    company: "İmbat Radyo ve Televizyon Yayıncılığı A.Ş.",
    logo: "İmbat FM",
    license: "Bölgesel Karasal (R2), İnternet",
    broadcastType: "Genel",
    platforms: "Karasal, İnternet",
    address:
      "Cemal Gürsel Caddesi, Bostanlı Mahallesi, No:486, Kat:5 Karşıyaka, İzmir",
    websites: ["www.imbatfm.com", "www.kordonmedya.com"],
    phone: "+90 232 462 5456",
    email: "imbatfm@hotmail.com",
    kep: "imbatradyo@hs09.kep.tr",
    uets: "25999-52596-00890",
    manager: {
      name: "Ali Dönmez",
      email: "alidonmez01@gmail.com",
      phone: "0544 5357610",
    },
    representative: {
      name: "Esra Özçelik",
      phone: "0531 4302778",
      email: "esraozcelik1@gmail.com",
    },
    color: "from-blue-500 to-blue-700",
  },
  {
    id: "2",
    name: "Kordon FM",
    company: "Kordon Radyo ve Televizyon Yayıncılığı A.Ş.",
    logo: "Kordon FM",
    license: "Bölgesel Karasal (R2), İnternet",
    broadcastType: "Genel",
    platforms: "Karasal, İnternet",
    address:
      "Cemal Gürsel Caddesi, Bostanlı Mahallesi, No:486, Kat:5 Karşıyaka, İzmir",
    websites: ["www.kordonfm.com", "www.kordonmedya.com"],
    phone: "0232 462 5456",
    email: "kordonfm@hotmail.com",
    kep: "kordonradyo@hs09.kep.tr",
    uets: "25999-22451-76487",
    manager: {
      name: "Murat Dönmez",
      email: "mektebimulkiye@hotmail.com",
      phone: "0506 9096356",
    },
    representative: {
      name: "Esra Özçelik",
      phone: "0531 4302778",
      email: "esraozcelik1@gmail.com",
    },
    color: "from-green-500 to-green-700",
  },
  {
    id: "3",
    name: "Radyo Kordelya",
    company: "Özel İzmir 92.5 Genç FM Görsel ve İşitsel Medya Yayıncılığı A.Ş.",
    logo: "Radyo Kordelya",
    license: "Yerel, Karasal (R1), İnternet",
    broadcastType: "Genel",
    platforms: "Karasal, İnternet",
    address:
      "Cemal Gürsel Caddesi, Bostanlı Mahallesi, No:486, Kat:5 Karşıyaka, İzmir",
    websites: ["www.radyokordelya.com", "www.kordonmedya.com"],
    phone: "0232 462 5456",
    email: "radyokordelya@hotmail.com",
    kep: "radyokordelya@hs09.kep.tr",
    uets: "25999-41364-23438",
    manager: {
      name: "Murat Dönmez",
      email: "mektebimulkiye@hotmail.com",
      phone: "0506 9096356",
    },
    representative: {
      name: "Esra Özçelik",
      phone: "0531 4302778",
      email: "esraozcelik1@gmail.com",
    },
    color: "from-purple-500 to-purple-700",
  },
  {
    id: "4",
    name: "İmbat Slow",
    company: "Dönmez Radyo ve Televizyon Yayıncılığı A.Ş.",
    logo: "İmbat Slow",
    license: "Yerel, Karasal (R1), İnternet",
    broadcastType: "Genel",
    platforms: "Karasal, İnternet",
    address:
      "Cemal Gürsel Caddesi, Bostanlı Mahallesi, No:486, Kat:5 Karşıyaka, İzmir",
    websites: ["www.imbatslow.com", "www.kordonmedya.com"],
    phone: "0232 462 5456",
    email: "imbatslow@hotmail.com",
    kep: "donmezradyo@hs09.kep.tr",
    uets: "25919-78692-58139",
    manager: {
      name: "Murat Dönmez",
      email: "mektebimulkiye@hotmail.com",
      phone: "0506 9096356",
    },
    representative: {
      name: "Esra Özçelik",
      phone: "0531 4302778",
      email: "esraozcelik1@gmail.com",
    },
    color: "from-orange-500 to-orange-700",
  },
  {
    id: "5",
    name: "İmbat Haber",
    company: "Otoban Radyo ve Televizyon Yayıncılığı A.Ş.",
    logo: "İmbat Haber",
    license: "Bölgesel, Karasal (R2), İnternet",
    broadcastType: "Genel",
    platforms: "Karasal, İnternet",
    address:
      "Cemal Gürsel Caddesi, Bostanlı Mahallesi, No:486, Kat:5 Karşıyaka, İzmir",
    websites: ["www.imbathaber.net", "www.kordonmedya.com"],
    phone: "0232 462 5456",
    email: "imbathaber@hotmail.com",
    kep: "otobanradyo@hs09.kep.tr",
    uets: "25929-05395-99034",
    manager: {
      name: "Murat Dönmez",
      email: "mektebimulkiye@hotmail.com",
      phone: "0506 9096356",
    },
    representative: {
      name: "Esra Özçelik",
      phone: "0531 4302778",
      email: "esraozcelik1@gmail.com",
    },
    color: "from-red-500 to-red-700",
  },
  {
    id: "6",
    name: "Kordon TV",
    company: "Kordon Radyo ve Televizyon Yayıncılığı A.Ş.",
    logo: "Kordon TV",
    license: "Bölgesel Karasal (T2), İnternet",
    broadcastType: "Genel",
    platforms: "Karasal, İnternet",
    address:
      "Cemal Gürsel Caddesi, Bostanlı Mahallesi, No:486, Kat:5 Karşıyaka, İzmir",
    websites: ["www.kordontv.com", "www.kordonmedya.com"],
    phone: "0232 462 5456",
    email: "kordontv@hotmail.com",
    kep: "kordonradyo@hs09.kep.tr",
    uets: "25999-22451-76487",
    manager: {
      name: "Murat Dönmez",
      email: "mektebimulkiye@hotmail.com",
      phone: "0506 9096356",
    },
    representative: {
      name: "Esra Özçelik",
      phone: "0531 4302778",
      email: "esraozcelik1@gmail.com",
    },
    color: "from-teal-500 to-teal-700",
  },
];

// Turkish texts
export const stationsInformationTexts: RadioStationsTexts = {
  title: "Kordon Medya Grubu",
  subtitle: "Radyo ve Televizyon İstasyonları Künye Bilgileri",
  searchPlaceholder: "İstasyon adı veya şirket adı ile arama yapın...",
  downloadPdf: "PDF İndir",
  details: "Detaylar",
  noResults: "Arama kriterlerinize uygun istasyon bulunamadı.",
  noResultsDescription: "Lütfen farklı arama terimleri deneyin.",
  generalInfo: "Genel Bilgiler",
  contactInfo: "İletişim Bilgileri",
  authorities: "Yetkililer",
  responsibleManager: "Sorumlu Müdür",
  listenerRepresentative: "Dinleyici Temsilcisi",
  viewerRepresentative: "İzleyici Temsilcisi",
  broadcastLicense: "Yayın Lisansı",
  broadcastType: "Yayın Türü",
  broadcastPlatforms: "Yayın Ortamları",
  uetsAddress: "UETS Adresi",
  kepAddress: "KEP Adresi",
  websites: "Web Siteleri",
};
